name: build-gradle
description: build-gradle
inputs:
  java-version:
    description: java-version
    required: true
  java-distribution:
    description: java-distribution
    required: true
  gradle-version:
    description: gradle-version
    required: true
runs:
  using: composite
  steps:
    - id: setup-java
      name: setup java
      uses: actions/setup-java@v3.11.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
    - id: gradle-build
      name: gradle build
      uses: gradle/gradle-build-action@v2.4.0
      with:
        arguments: clean build -x test
        gradle-version: ${{ inputs.gradle-version }}
