apiVersion: v1
kind: Service
metadata:
  name: geeq-front-service
spec:
  type: NodePort
  selector:
    app: geeq-front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30010

