name: codedeploy
description: codedeploy
inputs:
  application-name:
    required: true
  role-to-assume:
    required: true
  aws-region:
    required: true
  aws-s3-bucket:
    required: true
  aws-ecr-registry:
    required: true
  image-tag:
    required: true
runs:
  using: composite
  steps:
    - id: configure-aws-credentials
      name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: ${{inputs.role-to-assume}}
        role-session-name: github-actions-session
        aws-region: ${{inputs.aws-region}}
    - id: build-appspec
      name: build appspec
      run: |
        sed -i -e 's/AWS_REGION/${{ inputs.aws-region }}/g' deploy.sh
        if [[ -e deployment.yaml ]]; then
          sed -i -e 's/AWS_ECR_REGISTRY/${{ inputs.aws-ecr-registry }}/g' deployment.yaml
          sed -i -e 's/IMAGE_TAG/${{ inputs.image-tag }}/g' deployment.yaml
        fi
      shell: bash
      working-directory: codedeploy/${{ inputs.application-name }}
    - id: appspec-s3-upload
      name: appspec s3 upload
      run: |
        zip -r ${{ inputs.application-name }}.zip ${{ inputs.application-name }}
        aws s3 cp ${{ inputs.application-name }}.zip s3://${{inputs.aws-s3-bucket}}/
      shell: bash
      working-directory: codedeploy
    - id: codedeploy
      name: codedeploy
      run: |
        aws deploy create-deployment \
          --application-name ${{ inputs.application-name }}-codedeploy-app \
          --deployment-group-name ${{ inputs.application-name }}-deployment-group \
          --s3-location bucket=${{inputs.aws-s3-bucket}},key=${{ inputs.application-name }}.zip,bundleType=zip \
          --deployment-config-name ${{ inputs.application-name }}-deployment-config \
          --region ${{inputs.aws-region}}
      shell: bash
