name: constant
description: constant
outputs:
  aws-region:
    description: aws-region
    value: ${{ steps.constant.outputs.aws-region }}
  java-version:
    description: java-version
    value: ${{ steps.constant.outputs.java-version }}
  java-distribution:
    description: java-distribution
    value: ${{ steps.constant.outputs.java-distribution }}
  gradle-version:
    description: gradle-version
    value: ${{ steps.constant.outputs.gradle-version }}
  go-version:
    description: go-version
    value: ${{ steps.constant.outputs.go-version }}
  node-version:
    description: node-version
    value: ${{ steps.constant.outputs.node-version }}
runs:
  using: composite
  steps:
    - id: constant
      run: |
        echo "aws-region=ap-northeast-1" >> $GITHUB_OUTPUT
        echo "java-version=17" >> $GITHUB_OUTPUT
        echo "java-distribution=temurin" >> $GITHUB_OUTPUT
        echo "gradle-version=7.4.2" >> $GITHUB_OUTPUT
        echo "go-version=1.19.0" >> $GITHUB_OUTPUT
        echo "node-version=v20.0.0" >> $GITHUB_OUTPUT
      shell: bash
