name: constant
description: constant
outputs:
  aws-region:
    value: ${{ steps.constant.outputs.aws-region }}
runs:
  using: composite
  steps:
    - id: constant
      run: |
        echo "aws-region=ap-northeast-1" >> $GITHUB_OUTPUT
      shell: bash
