apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeus-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeus-api
  template:
    metadata:
      labels:
        app: zeus-api
    spec:
      containers:
        - name: zeus-api
          image: AWS_ECR_REGISTRY/zeus-api-repository:IMAGE_TAG
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-config
