apiVersion: v1
kind: Service
metadata:
  name: suzu-api-service
spec:
  type: NodePort
  selector:
    app: suzu-api
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30007
