name: docker-image-push
description: docker-image-push
inputs:
  role-to-assume:
    description: role-to-assume
    required: true
  aws-region:
    description: aws-region
    required: true
  aws-ecr-registry:
    description: aws-ecr-registry
    required: true
  docker-image-name:
    description: docker-image-name
    required: true
  dockerfile-path:
    description: dockerfile-path
    required: true
    default: .
runs:
  using: composite
  steps:
    - id: configure-aws-credentials
      name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2.0.0
      with:
        role-to-assume: ${{inputs.role-to-assume}}
        role-session-name: github-actions-role
        aws-region: ${{inputs.aws-region}}
    - id: image-build
      name: image build
      run: docker build -t ${{ inputs.aws-ecr-registry }}/${{ inputs.docker-image-name }} ${{ inputs.dockerfile-path }}
      shell: bash
    - id: push-image
      name: push image
      run: |
        aws ecr get-login-password --region ${{inputs.aws-region}} | docker login --username AWS --password-stdin ${{ inputs.aws-ecr-registry }}
        docker push ${{ inputs.aws-ecr-registry }}/${{ inputs.docker-image-name }}
      shell: bash
