name: build-cargo
description: build-cargo
inputs:
  rust-version:
    description: rust-version
    required: true
runs:
  using: composite
  steps:
    - id: setup-rustup
      name: setup rustup
      uses: ningenMe/setup-rustup@v1.0.1
      with:
        version: ${{ inputs.rust-version }}
    - id: build
      name: build
      run: |
        cargo build --release
      shell: bash
