apiVersion: apps/v1
kind: Deployment
metadata:
  name: nina-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nina-api
  template:
    metadata:
      labels:
        app: nina-api
    spec:
      containers:
        - name: nina-api
          image: AWS_ECR_REGISTRY/nina-api-repository:IMAGE_TAG
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: env-config
