apiVersion: v1
kind: Service
metadata:
  name: nina-envoy-service
spec:
  type: NodePort
  selector:
    app: nina-envoy
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30003
