apiVersion: apps/v1
kind: Deployment
metadata:
  name: miiko-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miiko-api
  template:
    metadata:
      labels:
        app: miiko-api
    spec:
      containers:
        - name: miiko-api
          image: AWS_ECR_REGISTRY/miiko-api-repository:IMAGE_TAG
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: env-config
