apiVersion: v1
kind: Service
metadata:
  name: miiko-api-service
spec:
  type: NodePort
  selector:
    app: miiko-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30006
