apiVersion: v1
kind: Service
metadata:
  name: geeq-api-service
spec:
  type: NodePort
  selector:
    app: geeq-api
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30008
