name: build-yarn
description: build-yarn
inputs:
  node-version:
    description: node-version
    required: true
runs:
  using: composite
  steps:
    - id: setup-node
      name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - id: yarn
      name: yarn
      run: |
        yarn install
        yarn build
      shell: bash
