apiVersion: batch/v1
kind: CronJob
metadata:
  name: suzu-batch
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: suzu-batch
            image: AWS_ECR_REGISTRY/suzu-batch-repository:IMAGE_TAG
            envFrom:
              - configMapRef:
                  name: env-config
          restartPolicy: Never
