apiVersion: v1
kind: Service
metadata:
  name: roman-api-service
spec:
  type: NodePort
  selector:
    app: roman-api
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30003
