name: all-deploy

on:
  workflow_dispatch:

run-name: deploy all

jobs:
  all-deploy:
    strategy:
      matrix:
        application-name:
          - akari-front
          - nina-api
          - zeus-api
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      application-name: ${{ matrix.application-name }}
    secrets: inherit
