name: all-deploy

on:
  workflow_dispatch:

run-name: deploy all

jobs:
  constant:
    runs-on: ubuntu-latest
    outputs:
      aws-region: ${{ steps.constant.outputs.aws-region }}
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: constant
        name: constant
        uses: ./.github/workflows/composite/constant
  all-deploy:
    needs: [ constant ]
    strategy:
      matrix:
        application-name:
          - akari-front
          - nina-api
          - zeus-api
          - kiwa-api
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      application-name: ${{ matrix.application-name }}
      aws-region: ${{ needs.constant.outputs.aws-region }}
    secrets: inherit
