name: reusable-deploy

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      ROLE_TO_ASSUME:
        required: true
      AWS_ECR_REGISTRY:
        required: true
      AWS_S3_BUCKET:
        required: true

jobs:
  codedeploy:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: get-image-tag
        name: get image tag
        if: ${{ inputs.application-name != 'env-config' && inputs.application-name != 'proxy' }}
        uses: ./.github/workflows/composite/get-image-tag
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws-region }}
          aws-ecr-registry: ${{ secrets.AWS_ECR_REGISTRY }}
          aws-ecr-repository: ${{ inputs.application-name }}-repository
      - id: codedeploy
        name: codedeploy
        uses: ./.github/workflows/composite/codedeploy
        with:
          application-name: ${{ inputs.application-name }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws-region }}
          aws-s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws-ecr-registry: ${{ secrets.AWS_ECR_REGISTRY }}
          image-tag: ${{ steps.get-image-tag.outputs.image-tag }}
