name: single-deploy

on:
  workflow_dispatch:

jobs:
  reusable-deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      application-name: akari-front
    secrets: inherit
