name: single-deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  reusable-deploy:
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      application-name: akari-front
