name: single-deploy

on:
  workflow_dispatch:
    inputs:
      application-name:
        description: 'application-name'
        required: true
        default: akari-front
        type: choice
        options:
          - akari-front
          - nina-api
          - zeus-api
          - kiwa-api
          - miiko-api

run-name: deploy ${{ inputs.application-name }}

jobs:
  constant:
    runs-on: ubuntu-latest
    outputs:
      aws-region: ${{ steps.constant.outputs.aws-region }}
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: constant
        name: constant
        uses: ./.github/workflows/composite/constant
  reusable-deploy:
    needs: [ constant ]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      application-name: ${{ inputs.application-name }}
      aws-region: ${{ needs.constant.outputs.aws-region }}
    secrets: inherit
