apiVersion: v1
kind: Service
metadata:
  name: akari-front-service
spec:
  type: NodePort
  selector:
    app: akari-front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001

